---
server:
  servlet:
    context-path: /api/v1
  error:
    include-stacktrace: on_param

application:
  phone-booking-queue: phone.booking.queue
spring:
  datasource:
    url: jdbc:h2:file:./db/phones;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  activemq:
    pool:
      enabled: false
    broker-url: vm://embedded?broker.persistent=false,useShutdownHook=false
  jms:
    template:
      default-destination: phone.booking.queue